import React,{useLayoutEffect,useRef,useState,useEffect} from 'react';import {createPortal} from 'react-dom';import {AnimatePresence,motion,useReducedMotion} from 'motion/react';import {X,Check,Search,AlertTriangle} from '@geist-ui/icons';import GlideMenu from './primitives/GlideMenu';
export type MenuOption={label:string;description?:string;checked?:boolean;icon?:React.ReactNode;action?:()=>void;node?:React.ReactNode};
export function AnchoredMenu({anchor,items,onClose}:{anchor:HTMLElement|null;items:MenuOption[];onClose:()=>void}){const ref=useRef<HTMLDivElement>(null),reduce=useReducedMotion()||document.documentElement.dataset.motion==='off';const [box,setBox]=useState({left:0,top:0,origin:'50% 0',direction:6});
 const searchable=items.length>5;const [query,setQuery]=useState('');
 useEffect(()=>{setQuery('')},[anchor,items]);
 const q=query.trim().toLowerCase();
 const visible=searchable&&q?items.filter(o=>!o.label.trim()||(o.label+' '+(o.description||'')).toLowerCase().includes(q)):items;
 useLayoutEffect(()=>{if(!anchor||!ref.current)return;const r=anchor.getBoundingClientRect(),width=Math.min(310,innerWidth-24),height=Math.min(ref.current.scrollHeight,innerHeight-24),below=r.bottom+height+8<innerHeight;const left=Math.max(12,Math.min(r.left,innerWidth-width-12)),top=below?r.bottom+6:Math.max(12,r.top-height-6),x=Math.max(12,Math.min(width-12,r.left+r.width/2-left));setBox({left,top,origin:`${x}px ${below?'0':'100%'}`,direction:below?6:-6});ref.current.querySelector<HTMLInputElement>('[data-menu-search]')?.focus() ?? ref.current.querySelector('button')?.focus();},[anchor,items]);
 useEffect(()=>{if(!anchor)return;const click=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node)&&!anchor.contains(e.target as Node))onClose()};const resize=()=>onClose();document.addEventListener('pointerdown',click);window.addEventListener('resize',resize);return()=>{document.removeEventListener('pointerdown',click);window.removeEventListener('resize',resize)}},[anchor,onClose]);
 return createPortal(<AnimatePresence>{anchor&&<div ref={ref} className="native-popover-wrap" role="menu" style={{left:box.left,top:box.top}} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose();anchor.focus();}if(['ArrowDown','ArrowUp'].includes(e.key)&&document.activeElement?.tagName!=='INPUT'){e.preventDefault();const rows=[...ref.current!.querySelectorAll('[data-menu-row]')],index=rows.indexOf(document.activeElement as HTMLButtonElement);(rows[(index+(e.key==='ArrowDown'?1:-1)+rows.length)%rows.length] as HTMLElement)?.focus();}}}>{searchable&&<motion.div className="native-popover-search" initial={reduce?false:{opacity:0,y:10,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:reduce?0:6,scale:reduce?1:.98}} transition={{duration:reduce?0:.26,delay:reduce?0:.08,ease:[.16,1,.3,1]}} style={{transformOrigin:box.origin}}><Search size={15}/><input data-menu-search placeholder="Поиск…" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();ref.current?.querySelector<HTMLElement>('[data-menu-row]')?.focus()}e.stopPropagation()}} aria-label="Поиск по меню"/></motion.div>}<motion.div className="native-popover native-popover-attached" style={{transformOrigin:box.origin}} initial={reduce?false:{opacity:0,scale:.92,y:box.direction}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:reduce?1:.96,y:reduce?0:box.direction}} transition={{duration:reduce?0:.24,ease:[.16,1,.3,1]}} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();onClose();anchor.focus();}if(['ArrowDown','ArrowUp'].includes(e.key)&&document.activeElement?.tagName!=='INPUT'){e.preventDefault();const rows=[...ref.current!.querySelectorAll('[data-menu-row]')],index=rows.indexOf(document.activeElement as HTMLButtonElement);(rows[(index+(e.key==='ArrowDown'?1:-1)+rows.length)%rows.length] as HTMLElement)?.focus();}}}><GlideMenu>{visible.map((item,i)=>item.node?<div data-menu-block key={i} className="menu-block">{item.node}</div>:<button role="menuitem" data-menu-row key={i} onClick={()=>{onClose();item.action?.()}}>{item.icon}<span>{item.label}{item.description&&<small>{item.description}</small>}</span>{item.checked&&<Check size={13}/>}</button>)}{searchable&&!visible.length&&<div className="small-notice">Ничего не найдено</div>}</GlideMenu></motion.div></div>}</AnimatePresence>,document.body)
}
export function Dialog({open,title,children,onClose}:{open:boolean;title:string;children:React.ReactNode;onClose:()=>void}){const dialog=useRef<HTMLDivElement>(null);const reduce=useReducedMotion()||document.documentElement.dataset.motion==='off';useEffect(()=>{if(!open)return;const old=document.activeElement as HTMLElement;requestAnimationFrame(()=>dialog.current?.querySelector<HTMLElement>('input,button')?.focus());return()=>old?.focus()},[open]);return createPortal(<AnimatePresence>{open&&<motion.div className="native-dialog-shade" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:reduce?0:.15}} onClick={onClose}><motion.section ref={dialog} role="dialog" aria-modal="true" aria-label={title} className="native-dialog" initial={reduce?false:{opacity:0,y:14,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:reduce?0:8,scale:reduce?1:.98}} transition={{duration:reduce?0:.28,ease:[.16,1,.3,1]}} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=[...dialog.current!.querySelectorAll<HTMLElement>('button,input,textarea,[tabindex="0"]')].filter(n=>!(n as HTMLInputElement).disabled);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}}><div className="native-dialog-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Закрыть"><X size={18}/></button></div><div className="native-dialog-body">{children}</div></motion.section></motion.div>}</AnimatePresence>,document.body)}

// Keep viewport positioning outside Motion's transform. Portaling also avoids
// the app container's clipping/containment and follows the Android keyboard.
export function Toast({message,kind='ok',onClose}:{message:string;kind?:'ok'|'warn';onClose:()=>void}) {
 const [viewport,setViewport]=useState(()=>({left:window.visualViewport?.offsetLeft??0,top:window.visualViewport?.offsetTop??0,width:window.visualViewport?.width??window.innerWidth,height:window.visualViewport?.height??window.innerHeight}));
 const reduce=useReducedMotion()||document.documentElement.dataset.motion==='off';
 useEffect(()=>{const update=()=>setViewport({left:window.visualViewport?.offsetLeft??0,top:window.visualViewport?.offsetTop??0,width:window.visualViewport?.width??window.innerWidth,height:window.visualViewport?.height??window.innerHeight});window.addEventListener('resize',update);window.visualViewport?.addEventListener('resize',update);window.visualViewport?.addEventListener('scroll',update);return()=>{window.removeEventListener('resize',update);window.visualViewport?.removeEventListener('resize',update);window.visualViewport?.removeEventListener('scroll',update)}},[]);
 useEffect(()=>{if(!message)return;const t=setTimeout(onClose,6000);return()=>clearTimeout(t)},[message,onClose]);
 return createPortal(<div className="native-toast-region" style={{left:viewport.left,top:viewport.top,width:viewport.width,height:viewport.height}}><AnimatePresence>{message&&<motion.div className={'toast'+(kind==='warn'?' toast-warn':'')} role="status" initial={reduce?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:reduce?0:4}} transition={{duration:reduce?0:.2}}>{kind==='warn'?<AlertTriangle size={16}/>:<Check size={16}/>}<span>{message}</span><button className="toast-close" type="button" aria-label="Закрыть уведомление" onClick={onClose}><X size={18}/></button></motion.div>}</AnimatePresence></div>,document.body);
}
